name: CI
on:
  # События, которые запускают jobs
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# jobs запускаются параллельно, если не указана последовательность
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Deploy on the Same Server
        run: |
          ls&&docker-compose pull && docker-compose up -d --build
